---
ID: "a83b2cb6-dd5d-48b2-b7b4-b0044dddda03"
Parent: "1500430c-e78f-4fb4-8a1f-f57e9bb26ccb"
Template: "1500430c-e78f-4fb4-8a1f-f57e9bb26ccb"
Path: /sitecore/templates/Feature/JSS Rule Engine/RAG/RAGToolFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{02B34F76-C32D-48D8-9DDC-951770B4B84A}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "390b7648-6992-4917-9a04-6bc846be3e39"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "060658c9-1495-471e-92fa-0692eefafa0e"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: RAG Tools
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250705T075017Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jack.spektor@akqa.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jack.spektor@akqa.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e479fbf6-0ebd-4362-94b6-569e11d7f06b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jack.spektor@akqa.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250705T080919Z
